
'use client';
import {
  collection,
  writeBatch,
  doc,
  Firestore,
  serverTimestamp,
  Timestamp,
  runTransaction,
  Transaction,
} from 'firebase/firestore';
import { eachDayOfInterval, format, differenceInCalendarDays } from 'date-fns';
import { errorEmitter } from '@/firebase/error-emitter';
import { FirestorePermissionError } from '@/firebase/errors';

// Define a TypeScript interface for the booking data
export interface BookingData {
  id?: string; // Optional because it's generated by Firestore
  fullName: string;
  email: string;
  phone: string;
  checkIn: Date | Timestamp;
  checkOut: Date | Timestamp;
  roomType: string;
  guests: string;
  paymentMethod: 'card' | 'property';
  createdAt?: Timestamp;
  status?: string;
  totalPrice?: number;
}

const roomPrices: { [key: string]: number } = {
    'single': 380,
    'double': 450,
    'deluxe': 750,
}

export const createBooking = async (db: Firestore, bookingData: Omit<BookingData, 'id' | 'createdAt' | 'status' | 'totalPrice'>) => {
  
  try {
    await runTransaction(db, async (transaction: Transaction) => {
      const bookingsCollection = collection(db, 'bookings');
      const newBookingRef = doc(bookingsCollection);
      const availabilityCollection = collection(db, 'availability');

      const checkInDate = bookingData.checkIn instanceof Date ? bookingData.checkIn : (bookingData.checkIn as Timestamp).toDate();
      const checkOutDate = bookingData.checkOut instanceof Date ? bookingData.checkOut : (bookingData.checkOut as Timestamp).toDate();
      
      const numberOfNights = differenceInCalendarDays(checkOutDate, checkInDate);
      const roomPrice = roomPrices[bookingData.roomType] || 0;
      const totalPrice = numberOfNights * roomPrice;

      // --- ALL READS MUST HAPPEN FIRST ---

      const bookedDates = eachDayOfInterval({
        start: checkInDate,
        end: checkOutDate,
      });
      
      if (bookedDates.length > 0) {
        bookedDates.pop(); // The last day is the checkout day, so it's available.
      }

      // Prepare to read all necessary availability docs
      const availabilityReads: Promise<{
          docRef: any;
          docSnap: any;
          dateString: string;
      }>[] = bookedDates.map(async (date) => {
          const dateString = format(date, 'yyyy-MM-dd');
          const availabilityDocRef = doc(availabilityCollection, dateString);
          const availabilityDoc = await transaction.get(availabilityDocRef);
          return { docRef: availabilityDocRef, docSnap: availabilityDoc, dateString };
      });
      
      const availabilityDocs = await Promise.all(availabilityReads);

      // --- ALL WRITES HAPPEN AFTER READS ---

      // 1. Write the main booking document
      const dataToSave = {
        ...bookingData,
        checkIn: Timestamp.fromDate(checkInDate),
        checkOut: Timestamp.fromDate(checkOutDate),
        createdAt: serverTimestamp(),
        status: 'Confirmed',
        totalPrice: totalPrice,
      };
      transaction.set(newBookingRef, dataToSave);

      // 2. Write the availability updates
      for (const { docRef, docSnap, dateString } of availabilityDocs) {
        if (!docSnap.exists()) {
          // If the doc for this date doesn't exist, create it.
          transaction.set(docRef, {
            date: dateString,
            [bookingData.roomType]: 1,
          });
        } else {
          // If it exists, increment the count for the specific room type.
          const currentCount = docSnap.data()[bookingData.roomType] || 0;
          transaction.update(docRef, {
            [bookingData.roomType]: currentCount + 1,
          });
        }
      }
    });

  } catch (error) {
    console.error("Error creating booking:", error);

    const permissionError = new FirestorePermissionError({
        path: 'bookings or availability', // This is a transaction, so path is indicative
        operation: 'create',
        requestResourceData: bookingData,
    });

    errorEmitter.emit('permission-error', permissionError);

    throw error; // Re-throw original error to be caught by the UI
  }
};
