
'use client';
import {
  collection,
  writeBatch,
  doc,
  Firestore,
  serverTimestamp,
  Timestamp,
  runTransaction,
  Transaction,
} from 'firebase/firestore';
import { eachDayOfInterval, format, differenceInCalendarDays } from 'date-fns';
import { errorEmitter } from '@/firebase/error-emitter';
import { FirestorePermissionError } from '@/firebase/errors';
import { roomData as allRoomData } from '@/lib/room-data';

// Define a TypeScript interface for the booking data
export interface BookingData {
  id?: string; // Optional because it's generated by Firestore
  fullName: string;
  email: string;
  phone: string;
  checkIn: Date | Timestamp;
  checkOut: Date | Timestamp;
  roomType: string;
  guests: string;
  paymentMethod: 'card' | 'property';
  createdAt?: Timestamp;
  status?: string;
  totalPrice?: number;
}

const roomPrices = allRoomData.reduce((acc, room) => {
    acc[room.type] = room.price;
    return acc;
}, {} as { [key: string]: number });


export const createBooking = async (db: Firestore, bookingData: Omit<BookingData, 'id' | 'createdAt' | 'status' | 'totalPrice'>) => {
  
  try {
    await runTransaction(db, async (transaction: Transaction) => {
      const bookingsCollection = collection(db, 'bookings');
      const newBookingRef = doc(bookingsCollection);
      const availabilityCollection = collection(db, 'availability');

      const checkInDate = bookingData.checkIn instanceof Date ? bookingData.checkIn : (bookingData.checkIn as Timestamp).toDate();
      const checkOutDate = bookingData.checkOut instanceof Date ? bookingData.checkOut : (bookingData.checkOut as Timestamp).toDate();
      
      const numberOfNights = differenceInCalendarDays(checkOutDate, checkInDate);
      const roomPrice = roomPrices[bookingData.roomType] || 0;
      const totalPrice = numberOfNights * roomPrice;

      // --- ALL READS MUST HAPPEN FIRST ---

      const bookedDatesInterval = eachDayOfInterval({
        start: checkInDate,
        end: checkOutDate,
      });
      
      // The last day is the checkout day, so it's available for the next guest.
      if (bookedDatesInterval.length > 0) {
        bookedDatesInterval.pop(); 
      }

      // Prepare to read all necessary availability docs
      const availabilityReads = bookedDatesInterval.map(date => {
          const dateString = format(date, 'yyyy-MM-dd');
          const availabilityDocRef = doc(availabilityCollection, dateString);
          return transaction.get(availabilityDocRef);
      });
      
      const availabilityDocsSnaps = await Promise.all(availabilityReads);

      // --- ALL WRITES HAPPEN AFTER READS ---

      // 1. Write the main booking document
      const dataToSave = {
        ...bookingData,
        checkIn: Timestamp.fromDate(checkInDate),
        checkOut: Timestamp.fromDate(checkOutDate),
        createdAt: serverTimestamp(),
        status: 'Confirmed',
        totalPrice: totalPrice,
      };
      transaction.set(newBookingRef, dataToSave);

      // 2. Write the availability updates
      availabilityDocsSnaps.forEach((docSnap, index) => {
        const dateString = format(bookedDatesInterval[index], 'yyyy-MM-dd');
        const docRef = doc(availabilityCollection, dateString);

        if (!docSnap.exists()) {
          // If the doc for this date doesn't exist, create it.
          transaction.set(docRef, {
            date: dateString,
            [bookingData.roomType]: 1,
          });
        } else {
          // If it exists, increment the count for the specific room type.
          const currentCount = docSnap.data()?.[bookingData.roomType] || 0;
          transaction.update(docRef, {
            [bookingData.roomType]: currentCount + 1,
          });
        }
      });
    });

  } catch (error) {
    console.error("Error creating booking:", error);

    const permissionError = new FirestorePermissionError({
        path: 'bookings or availability', // This is a transaction, so path is indicative
        operation: 'create',
        requestResourceData: bookingData,
    });

    errorEmitter.emit('permission-error', permissionError);

    throw error; // Re-throw original error to be caught by the UI
  }
};


export const deleteBooking = async (
    db: Firestore,
    bookingId: string,
    roomType: string,
    checkIn: Date,
    checkOut: Date
) => {
    try {
        await runTransaction(db, async (transaction: Transaction) => {
            const bookingRef = doc(db, 'bookings', bookingId);
            const availabilityCollection = collection(db, 'availability');
            
            // --- ALL READS FIRST ---
            
            const bookedDatesInterval = eachDayOfInterval({ start: checkIn, end: checkOut });
             if (bookedDatesInterval.length > 0) {
                bookedDatesInterval.pop(); // Don't adjust checkout day
            }
            
            const availabilityReads = bookedDatesInterval.map(date => {
                const dateString = format(date, 'yyyy-MM-dd');
                const availabilityDocRef = doc(availabilityCollection, dateString);
                return transaction.get(availabilityDocRef);
            });
            await Promise.all(availabilityReads); // ensure reads happen


            // --- ALL WRITES AFTER ---

            // 1. Delete the booking document
            transaction.delete(bookingRef);

            // 2. Decrement availability for each date in the booking
            bookedDatesInterval.forEach(date => {
                const dateString = format(date, 'yyyy-MM-dd');
                const availabilityDocRef = doc(availabilityCollection, dateString);
                
                // We've already read this in the Promise.all above, so we can just update
                // This will fail if the doc doesn't exist, but it should exist if a booking was made.
                // We use dot notation which is required for field transforms.
                const fieldName = `${roomType}`;
                transaction.update(availabilityDocRef, {
                    [fieldName]: (
                        (doc(availabilityCollection, dateString) as any)[fieldName] || 1
                    ) -1
                });
            });
        });
    } catch (error) {
        console.error('Error deleting booking:', error);
        
        const permissionError = new FirestorePermissionError({
            path: `bookings/${bookingId}`,
            operation: 'delete',
        });
        errorEmitter.emit('permission-error', permissionError);
        
        throw error;
    }
};
