
'use client';
import {
  collection,
  writeBatch,
  doc,
  Firestore,
  serverTimestamp,
  Timestamp,
} from 'firebase/firestore';
import { eachDayOfInterval, format, differenceInCalendarDays } from 'date-fns';
import { errorEmitter } from '@/firebase/error-emitter';
import { FirestorePermissionError } from '@/firebase/errors';

// Define a TypeScript interface for the booking data
export interface BookingData {
  id?: string; // Optional because it's generated by Firestore
  fullName: string;
  email: string;
  phone: string;
  checkIn: Date | Timestamp;
  checkOut: Date | Timestamp;
  roomType: string;
  guests: string;
  paymentMethod: 'card' | 'property';
  createdAt?: Timestamp;
  status?: string;
  totalPrice?: number;
}

const roomPrices: { [key: string]: number } = {
    'single': 380,
    'double': 450,
    'deluxe': 750,
}

export const createBooking = async (db: Firestore, bookingData: Omit<BookingData, 'id' | 'createdAt' | 'status' | 'totalPrice'>) => {
  const batch = writeBatch(db);

  try {
    const bookingsCollection = collection(db, 'bookings');
    const newBookingRef = doc(bookingsCollection);

    const checkInDate = bookingData.checkIn instanceof Date ? bookingData.checkIn : (bookingData.checkIn as Timestamp).toDate();
    const checkOutDate = bookingData.checkOut instanceof Date ? bookingData.checkOut : (bookingData.checkOut as Timestamp).toDate();
    
    const numberOfNights = differenceInCalendarDays(checkOutDate, checkInDate);
    const roomPrice = roomPrices[bookingData.roomType] || 0;
    const totalPrice = numberOfNights * roomPrice;

    const dataToSave = {
      ...bookingData,
      checkIn: Timestamp.fromDate(checkInDate),
      checkOut: Timestamp.fromDate(checkOutDate),
      createdAt: serverTimestamp(),
      status: 'Confirmed',
      totalPrice: totalPrice,
    };
    batch.set(newBookingRef, dataToSave);

    const availabilityCollection = collection(db, 'availability');
    const bookedDates = eachDayOfInterval({
      start: checkInDate,
      end: checkOutDate,
    });
    
    if (bookedDates.length > 0) {
      bookedDates.pop();
    }

    bookedDates.forEach(date => {
      const dateString = format(date, 'yyyy-MM-dd');
      const availabilityDocId = `${bookingData.roomType}_${dateString}`;
      const availabilityDocRef = doc(availabilityCollection, availabilityDocId);
      
      batch.set(availabilityDocRef, {
        roomType: bookingData.roomType,
        date: dateString,
        bookingId: newBookingRef.id,
      });
    });

    await batch.commit();

  } catch (error) {
    console.error("Error creating booking:", error);

    const permissionError = new FirestorePermissionError({
        path: 'bookings or availability', // This is a batch write, so path is indicative
        operation: 'create',
        requestResourceData: bookingData,
    });

    errorEmitter.emit('permission-error', permissionError);

    throw error; // Re-throw original error to be caught by the UI
  }
};
